core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from records.views import e_handler404, e_handler500


urlpatterns = [
    path('', include('records.urls')),
    path('admin/', admin.site.urls),
]


handler404 = e_handler404
handler500 = e_handler500


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

records/urls.py
from django.urls import path

app_name = 'records'

from .views import (
    index,
    get_hotels, get_hotel,
    get_restaurants, get_restaurant,
    get_pois, get_poi,
    get_guide,
    get_tours, get_tour,
    get_organizations, get_organization,
    get_posts, get_post,
    get_transports, get_transport,
    get_events, get_event,
    subscribe,
    search,
    get_feedback_form,
    show404
)

urlpatterns = [
    path('', index, name='index'),

    path('hotels/', get_hotels, name='hotel-list'),
    path('hotels/<int:pk>', get_hotel, name='hotel-detail'),

    path('restaurants/', get_restaurants, name='restaurant-list'),
    path('restaurants/<int:pk>', get_restaurant, name='restaurant-detail'),

    path('guides/<int:pk>', get_guide, name='guide-detail'),

    path('tours/', get_tours, name='tour-list'),
    path('tours/<int:pk>', get_tour, name='tour-detail'),

    path('organizations/', get_organizations, name='organization-list'),
    path('organization/<int:pk>', get_organization, name='organization-detail'),

    path('posts/', get_posts, name='post-list'),
    path('posts/<int:pk>', get_post, name='post-detail'),

    path('point-of-interests/', get_pois, name='poi-list'),
    path('point-of-interests/<int:pk>', get_poi, name='poi-detail'),

    path('transports/', get_transports, name='transport-list'),
    path('transports/<int:pk>', get_transport, name='transport-detail'),

    path('events/', get_events, name='event-list'),
    path('events/<int:pk>', get_event, name='event-detail'),

    path('posts/', get_posts, name='post-list'),
    path('post/<int:pk>', get_post, name='post-detail'),

    path('subscribe/', subscribe, name='subscribe'),
    path('search/', search, name='search'),

    path('feedback/', get_feedback_form, name='feedback'),

    path('404/', show404, name='404'),

]

templates/layouts/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
{% include 'includes/head.html' %}
<body>
{% block content %} {% endblock %}
{% include 'includes/footer.html' %}

<script defer>
    let form = document.getElementById('subscription-form')


    form.addEventListener('submit', event => {
        event.preventDefault()

        let email = document.getElementById('email-for-subscription')

        if (email.value.trim().length > 0) { // fix this shit - add proper validation
            postJSON({email: email.value})
        }
        // do something if email is not valid
    })


    async function postJSON(data) {
        try {
            const response = await fetch("{% url 'records:subscribe' %}", {
                method: "POST", // or 'PUT'
                headers: {
                    "Content-Type": "application/json",
                    "X-CSRFToken": '{{ csrf_token }}'
                },
                body: JSON.stringify(data)
            });

            const result = await response.json()

            console.log(result)

            if (result.message === 'Subscribed') {
                const dialog = document.getElementById("modalsuccess")
                dialog.showModal()
            }

            if (result.message === 'Duplicate found') {
                const dialog = document.getElementById("modalduplicate")
                dialog.showModal()
            }
        } catch (error) {
            const dialog = document.getElementById("modalerror")
            dialog.showModal()
        }
    }
</script>

<script>
    let menuToggleBtn = document.getElementById('hamburger-btn')
    let navItems = document.getElementById('mobile-nav-items')

    menuToggleBtn.addEventListener('click', () => {
        navItems.classList.toggle('show')
    })
</script>

<dialog id="modalsuccess" class="modal">
    <h1>Спасибо за подписку!</h1>
    <p>Теперь вы сможете получать актуальную информацию об обновлениях данного ресурса.</p>
    <form method="dialog">
        <button>&#10005;</button>
    </form>
</dialog>

<dialog id="modalduplicate" class="modal">
    <h1>Данная электронная почта уже подписана на обновления!</h1>
    <form method="dialog">
        <button>&#10005;</button>
    </form>
</dialog>

<dialog id="modalerror" class="modal">
    <h1>Что-то пошло не так!</h1>
    <p>Попробуйте снова. В этот раз попробуйте стандартный формат электронной почты (напр. test@test.uz)</p>
    <form method="dialog">
        <button>&#10005;</button>
    </form>
</dialog>

</body>
</html>