core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from records.views import e_handler404, e_handler500


urlpatterns = [
    path('', include('records.urls')),
    path('admin/', admin.site.urls),
]


handler404 = e_handler404
handler500 = e_handler500


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

records/urls.py
from django.urls import path

app_name = 'records'

from .views import (
    index,
    get_hotels, get_hotel,
    get_restaurants, get_restaurant,
    get_pois, get_poi,
    get_guide,
    get_tours, get_tour,
    get_organizations, get_organization,
    get_posts, get_post,
    get_transports, get_transport,
    get_events, get_event,
    subscribe,
    search,
    get_feedback_form,
    show404
)

urlpatterns = [
    path('', index, name='index'),

    path('hotels/', get_hotels, name='hotel-list'),
    path('hotels/<int:pk>', get_hotel, name='hotel-detail'),

    path('restaurants/', get_restaurants, name='restaurant-list'),
    path('restaurants/<int:pk>', get_restaurant, name='restaurant-detail'),

    path('guides/<int:pk>', get_guide, name='guide-detail'),

    path('tours/', get_tours, name='tour-list'),
    path('tours/<int:pk>', get_tour, name='tour-detail'),

    path('organizations/', get_organizations, name='organization-list'),
    path('organization/<int:pk>', get_organization, name='organization-detail'),

    path('posts/', get_posts, name='post-list'),
    path('posts/<int:pk>', get_post, name='post-detail'),

    path('point-of-interests/', get_pois, name='poi-list'),
    path('point-of-interests/<int:pk>', get_poi, name='poi-detail'),

    path('transports/', get_transports, name='transport-list'),
    path('transports/<int:pk>', get_transport, name='transport-detail'),

    path('events/', get_events, name='event-list'),
    path('events/<int:pk>', get_event, name='event-detail'),

    path('posts/', get_posts, name='post-list'),
    path('post/<int:pk>', get_post, name='post-detail'),

    path('subscribe/', subscribe, name='subscribe'),
    path('search/', search, name='search'),

    path('feedback/', get_feedback_form, name='feedback'),

    path('404/', show404, name='404'),

]

records/models.py
from django.db import models
from django.urls import reverse
from location_field.models.plain import PlainLocationField

from helpers.utils import path_and_rename


class Guide(models.Model):
    first_name = models.CharField('Имя', max_length=100, null=False, blank=False)
    last_name = models.CharField('Фамилия', max_length=100, null=False, blank=False)
    middle_name = models.CharField('Отчество', max_length=100, null=True, blank=True)

    SEX_CHOICES = (('Male', 'Мужчина'), ('Female', 'Женщина'))
    sex = models.CharField('Пол', max_length=20, choices=SEX_CHOICES, blank=True, null=True, default='Male')
    age = models.PositiveIntegerField('Возраст', null=True, blank=True)
    image = models.ImageField('Фотография', upload_to=path_and_rename('uploads/guides'), blank=True, null=True)

    daily_fee = models.PositiveIntegerField('Стоимость услуг за день (в сумах)', null=True, blank=True)
    email = models.CharField('Электронная почта', max_length=100, null=True, blank=True)
    phone = models.CharField('Телефон', max_length=100, null=True, blank=True)
    telegram = models.CharField('Telegram', max_length=100, null=True, blank=True)
    facebook = models.CharField('Фейбук', max_length=100, null=True, blank=True)
    instagram = models.CharField('Инстаграм', max_length=100, null=True, blank=True)

    notes = models.TextField('Дополнительная информация', null=True, blank=True)

    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    def get_absolute_url(self):
        return reverse('records:guide-detail', kwargs={'pk': self.pk})

    def get_fullname(self):
        return f'{self.first_name} {self.last_name}'

    class Meta:
        ordering = ['-created']
        verbose_name = 'Гид'
        verbose_name_plural = 'Гиды'


class Restaurant(models.Model):
    title = models.CharField(max_length=100, null=False, blank=False)
    main_image = models.ImageField(upload_to=path_and_rename('uploads/restaurants'), null=True, blank=True)
    description = models.TextField('Краткое описание', max_length=1000, null=True, blank=True)
    average_bill = models.PositiveIntegerField('Средний счет на 1 человека', default=0)

    address = models.CharField('Адрес', max_length=500, null=True, blank=True)
    phone = models.CharField(max_length=100, null=True, blank=True)
    email = models.CharField(max_length=100, null=True, blank=True)
    facebook = models.CharField(max_length=100, null=True, blank=True)
    instagram = models.CharField(max_length=100, null=True, blank=True)
    telegram = models.CharField(max_length=100, null=True, blank=True)

    city = models.CharField(max_length=255, null=True, blank=True, default='Shahrisabz')
    location = PlainLocationField(based_fields=['city'], default='39.060366, 66.845915', zoom=7)

    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created']
        verbose_name = 'Ресторан'
        verbose_name_plural = 'Рестораны'

    def get_absolute_url(self, **kwargs):
        return reverse('records:restaurant-detail', kwargs={'pk': self.id})


class Meal(models.Model):
    title = models.CharField('Название пункта меню', max_length=200, null=False, blank=False)
    price = models.PositiveIntegerField('Цена одной единицы')
    restaurant_attached = models.ForeignKey('Restaurant', null=True, blank=True, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=path_and_rename('uploads/meals'), null=True, blank=True)

    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created']
        verbose_name = 'Пункт меню'
        verbose_name_plural = 'Пункты меню'


class RestaurantImage(models.Model):
    image = models.ImageField(upload_to=path_and_rename('uploads/restaurants'), null=True, blank=True)
    # TODO: main image is duplicated in model and here - fix it later
    restaurant_attached = models.ForeignKey('Restaurant', null=True, blank=True, on_delete=models.CASCADE)
    caption = models.CharField('Описание к изображнию', max_length=200, null=True, blank=True)

    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)

    class Meta:
        ordering = ['caption']
        verbose_name = 'Изображение ресторана'
        verbose_name_plural = 'Изображения ресторана'

    def __str__(self) -> str:
        return f'{self.caption}'


class Hotel(models.Model):
    title = models.CharField('Название', max_length=100, null=False, blank=False)
    description = models.TextField('Описание', max_length=1000, null=True, blank=True)
    address = models.TextField('Адрес', max_length=1000, null=True, blank=True)
    main_image = models.ImageField(upload_to=path_and_rename('uploads/hotels'), null=True, blank=True)

    notes = models.TextField('Дополнительная информация', null=True, blank=True)

    city = models.CharField('Город', max_length=255, null=True, blank=True, default='Shahrisabz')
    location = PlainLocationField(based_fields=['city'], default='39.060366, 66.845915', zoom=7)

    phone = models.CharField('Телефон', max_length=100, null=True, blank=True)
    email = models.CharField('Электронная почта', max_length=100, null=True, blank=True)
    telegram = models.CharField('Телеграм', max_length=100, null=True, blank=True)
    facebook = models.CharField('Фейсбук', max_length=100, null=True, blank=True)
    instagram = models.CharField('Инстаграм', max_length=100, null=True, blank=True)

    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created']
        verbose_name = 'Отель'
        verbose_name_plural = 'Отели'

    def get_absolute_url(self, **kwargs):
        return reverse('records:hotel-detail', kwargs={'pk': self.id})

    def get_lowest_price(self):
        prices = []
        for room in self.hotelroom_set.all():
            prices.append(room.price)
        return min(prices)


class HotelRoom(models.Model):
    title = models.CharField('Название комнаты', max_length=200, null=False, blank=False)
    price = models.PositiveIntegerField('Цена комнаты')
    hotel_attached = models.ForeignKey('Hotel', null=True, blank=True, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=path_and_rename('uploads/rooms'), null=True, blank=True)

    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created']
        verbose_name = 'Комната отеля'
        verbose_name_plural = 'Комнаты отеля'


class HotelImage(models.Model):
    image = models.ImageField(upload_to=path_and_rename('uploads/hotels'), null=True, blank=True)
    # TODO: main image is duplicated in model and here - fix it later
    main = models.BooleanField('Главное изображение', default=False)
    hotel_attached = models.ForeignKey('Hotel', null=True, blank=True, on_delete=models.CASCADE)
    caption = models.CharField('Описание к изображнию', max_length=200, null=True, blank=True)

    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)

    class Meta:
        ordering = ['caption']
        verbose_name = 'Изображение отеля'
        verbose_name_plural = 'Изображения отеля'

    def __str__(self) -> str:
        return f'{self.caption}'


class Post(models.Model):
    title = models.CharField('Заголовок', max_length=100, null=False, blank=False)
    description = models.TextField('Текст поста', null=True, blank=True)
    image = models.ImageField('Изображение', upload_to=path_and_rename('uploads/posts'), null=True, blank=True)
    author = models.CharField('Автор', max_length=100, null=True, blank=True)

    date = models.DateField('Дата публикации')

    draft = models.BooleanField('Черновик', blank=False, null=False, default=False)

    TYPE_CHOICES = (('News', 'Новость'), ('Blog', 'Запись в блоге'), ('Other', 'Другое'))
    post_type = models.CharField('Тип публикации', max_length=20, choices=TYPE_CHOICES, blank=True, null=True,
                                 default='News')

    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created']
        verbose_name = 'Публикация'
        verbose_name_plural = 'Публикации'

    def get_absolute_url(self, **kwargs):
        return reverse('records:post-detail', kwargs={'pk': self.id})

    def posttype_verbose(self):
        return dict(Post.TYPE_CHOICES)[self.post_type]


class POI(models.Model):  # points of interest
    title = models.CharField('Название', max_length=100, null=False, blank=False)
    description = models.TextField('Описание', blank=True, null=True)
    address = models.CharField('Адрес', max_length=1000, null=True, blank=True)

    TYPE_CHOICES = (
        ('geology', 'Геологические объекты'),
        ('ecotourism', 'Объекты экотуризма'),
        ('info', 'Информационные центры'),
        ('craft', 'Туристические деревни и ремесла'),
        ('shrine', 'Cвятыни'),
        ('historical_places', 'Исторические места'),
        ('gastronomy', 'Гастрономические центры'),
        ('others', 'Другие'),
    )
    poi_type = models.CharField('Тип интереса', max_length=20, choices=TYPE_CHOICES, blank=True, null=True,
                                default='Event')

    city = models.CharField('Город', max_length=255, null=True, blank=True, default='Shahrisabz')
    location = PlainLocationField(based_fields=['city'], default='39.060366, 66.845915', zoom=7)

templates/event.html
{% extends 'layouts/base.html' %}
{% load extras %}

{% block content %}

    <header class="full-bleed">
        {% categories %}
    </header>

    <ul class="section breadcrumbs">
        <li><a href="{% url 'records:index' %}">Главная</a></li>
        <li><a href="{% url 'records:event-list' %}">{{ 'Все мероприятия / анонсы / события'|truncatechars:10 }}</a></li>
        <li><p>{{ event.title | truncatechars:20 }}</p></li>
    </ul>

    <main class="section page-hotels mt-2">
        <header>
            <h1>{{ event.title }}</h1>
            {% if event.address %}
            	<address><i class="fa-solid fa-location-dot"></i> {{ event.address }}</address>
            {% endif %}
            <strong class="price">{{ event.eventtype_verbose }}</strong>
        </header>

        {% if event.eventimage_set.all %}
            <ul class="gallery mt-2">
                {% for item in event.eventimage_set.all %}
                    <li><img src="{{ item.image.url }}" alt="{{ image.caption }}"/></li>
                {% endfor %}
            </ul>
        {% endif %}

        {% if event.description %}
            <section>
                <h3>Описание</h3>
                <p>{{ event.description }}</p>
            </section>
        {% endif %}

        <section class="map">
            <h3>Местоположение на карте</h3>
            <div id="map" style="width: 100%; height: 500px"></div>
        </section>
    </main>

     <script>
        let eventLoc = '{{ event.location }}'.split(',')

        let map = L.map('map').setView([eventLoc[0], eventLoc[1]], 13);

        L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
            maxZoom: 19,
            attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
        }).addTo(map);

        let marker = L.marker([
            eventLoc[0],
            eventLoc[1]
        ]).addTo(map);
    </script>

{% endblock content %}

templates/feedback.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load extras %}

{% block content %}

    <header class="full-bleed">
        {% categories %}
    </header>

    <ul class="breadcrumbs section">
        <li><a href="{% url 'records:index' %}">Главная</a></li>
        <li><p>Форма обратной связи</p></li>
    </ul>

    <div class="card section">
        <p class="{% if error %}feedback-msg-box-error{% endif %}{% if ok %}feedback-msg-box-success{% endif %}">{{ message }}</p>
        <h2 class="feedback-form-header">Напишите нам</h2>
        <div class="feedback-form-wrapper">
            <form action="{% url 'records:feedback' %}" method="POST" class="feedback-form">
                {% csrf_token %}
                <div class="feedback-form-group">
                    <input type="text" class="form-control block" placeholder="Ваше имя" name="full_name">
                    <input type="email" class="form-control block" placeholder="Ваша электронная почта" name="email">
                    <textarea rows="8" type="text" class="form-control block" placeholder="Ваше сообщение" name="message"></textarea>
                    <div class="fieldset">
                        <label>Кликните если вы человек *</label>
                        <script src="https://www.google.com/recaptcha/api.js" async defer></script>
                        <div class="g-recaptcha mt-15" data-sitekey="6LdDmNMoAAAAABj0JQvx7erspY0uRddOoPmSeFYD"></div>
                    </div>
                    <input type="submit" value="Отправить" class="btn">
                </div>
            </form>

            <div class="feedback-form-img">
                <img src="{% static 'images/fi.jpg' %}" alt="Статуя Амира Темура">
            </div>
        </div>
    </div>

{% endblock content %}

templates/hotel.html
{% extends 'layouts/base.html' %}
{% load extras %}

{% block content %}
    <header class="full-bleed">
        {% categories %}
    </header>

    <ul class="section breadcrumbs mt-2 mb-2">
        <li><a href="{% url 'records:index' %}">Главная</a></li>
        <li><a href="{% url 'records:hotel-list' %}">Все отели</a></li>
        <li>{{ hotel.title | truncatechars:20 }}</li>
    </ul>

    <main class="section page-hotels">
        <header>
            <h1>{{ hotel.title }}</h1>
            <address><i class="fa-solid fa-location-dot"></i> {{ hotel.address }}</address>
        </header>

        {% if hotel.hotelimage_set.all %}
            <ul class="gallery mt-2">
                {% for item in hotel.hotelimage_set.all %}
                    <li><img src="{{ item.image.url }}" alt="{{ image.caption }}"/></li>
                {% endfor %}
            </ul>
        {% endif %}

        {% if hotel.description %}
            <section class="section-description">
                <h3>Описание</h3>
                <p>{{ hotel.description }}</p>
            </section>
        {% endif %}

        {% if hotel.hotelroom_set.all %}
            <section class="room-list">
                <h3>Варианты размещения</h3>
                <ul class="list">
                    {% for room in hotel.hotelroom_set.all %}
                        <li id="{{ room.id }}">
                            <img class="hotel-image" src="{{ room.image.url }}" alt="{{ room.title }}">
                            <p>{{ room.title }}</p>
                            <strong>{{ room.price }} сум<small>/ночь</small></strong>
                        </li>
                    {% endfor %}
                </ul>
            </section>
        {% endif %}

        <section class="map">
            <h3>Местоположение на карте</h3>
            <div id="map" style="width: 100%; height: 500px"></div>
        </section>
    </main>

    <dialog id="img-modal" class="modal"></dialog>

    <script>
        let hotelLoc = '{{ hotel.location }}'.split(',')

        let map = L.map('map').setView([hotelLoc[0], hotelLoc[1]], 13);

        L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
            maxZoom: 19,
            attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
        }).addTo(map);

        let marker = L.marker([
            hotelLoc[0],
            hotelLoc[1]
        ]).addTo(map);
    </script>

    <script defer>
        let roomImages = document.querySelectorAll('.hotel-image')

        roomImages.forEach(img => {
            img.addEventListener('click', e => {
                let dialog = document.getElementById('img-modal')

                dialog.innerHTML = `<img src="${img.src}" alt="${img.alt}">
                                    <form method="dialog">
                                        <button>&#10005;</button>
                                    </form>`
                dialog.showModal()
            })
        })
    </script>
{% endblock content %}

templates/index.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load extras %}


{% block content %}
    <header class="header">

        {% categories %}

        {% if banner %}
            <div class="banner" style="background: url({{ banner.image.url }}) center center no-repeat; background-size: cover;">
                <div class="section">
                    <h1>{{ banner.first_line_text }}</h1>
                    <h1 class="main-text"><strong>{{ banner.second_line_text }}</strong></h1>
                    <p>{{ banner.third_line_text }}</p>
                </div>
            </div>
        {% else %}
            <div class="banner" style="background: url({% static 'images/bg-header.jpeg' %}) center center no-repeat; background-size: cover;">
                <div class="section">
                    <h1>Добро пожаловать в <strong>Шахрисабз!</strong></h1>
                    <p>Один из древнейших городов Узбекистана с историческим центром, внесенным в объекты Всемирного
                        наследия ЮНЕСКО.</p>
                </div>
            </div>
        {% endif %}

        <div class="section search-bar">
            <h2>Поиск по реестру</h2>
            <form action="{% url 'records:search' %}" method="GET">
                <div class="form-group horizontal">
                    <input type="text" id="name" class="form-control" placeholder="Отели, гиды, туры ..." name="query">
                    <input type="submit" value="Поиск" class="btn">
                </div>
            </form>
        </div>
    </header>

    <section class="section gallery-list mt-3">
        <header class="section-header">
            <h1>Проживание</h1>
            <p>Получите актуальную информацию про места для проживания в городе и районе Шахрисабз.</p>
            <a href="{% url 'records:hotel-list' %}" class="btn btn-primary btn-outline btn-small">Больше</a>
        </header>
        <ul class="horizontal mt-2">
            {% if hotels %}
                {% for hotel in hotels %}
                    <li class="vertical-card">
                        <article style="background-image: url('{{ hotel.main_image.url }}')">
                            <div class="info">
                                <header>
                                    <h1><a href="{{ hotel.get_absolute_url }}">{{ hotel.title }}</a></h1>
                                    <p>{{ hotel.description|truncatewords:10 }}</p>
                                </header>

                                {% if hotel.hotelroom_set.all %}
                                    <strong>от {{ hotel.get_lowest_price }} сум</strong>
                                {% endif %}
                            </div>
                        </article>
                    </li>
                {% endfor %}
            {% endif %}
        </ul>
    </section>

    <section class="section one-to-four mt-4">
        <header class="section-header">
            <h1>Точки интереса</h1>
            <p>Узнайте чем можно заняться и какие места можно посетить в городе и районе Шахрисабз.</p>
            <a href="{% url "records:poi-list" %}" class="btn btn-primary btn-outline btn-small">Больше</a>
        </header>

        <div class="items mt-2">
            {% if poi %}
                <article>
                    <header>
                        <h1>{{ poi.title }}</h1>
                        <p><strong>{{ poi.poitype_verbose }}</strong></p>
                    </header>
                    <p class="mt-2">{{ poi.description|truncatewords:20 }}</p>
                    <a href="{{ poi.get_absolute_url }}" class="btn btn-block btn-primary-contrast">Узнать больше</a>
                </article>
            {% endif %}

            {% if poi.poiimage_set.all %}
                <ul>
                    {% for image in poi.poiimage_set.all %}
                        <li><img src="{{ image.image.url }}" alt="{{ image.caption }}"></li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
    </section>

    {% if guides %}
        <section class="section guides-list mt-3">
            <header class="section-header">
                <h1>Местные гиды</h1>
                <p>Познакомьтесь с гидами, которые помогут вам ориентироваться в городе и районе Шахрисабз.</p>
            </header>

            <ul class="guide-cards mt-2">
                {% for guide in guides %}
                    <li class="card guide-card">
                        {% if guide.image %}
                            <img src="{{ guide.image.url }}" alt="{{ guide.get_fullname }}">
                        {% endif %}

                        <a href="{{ guide.get_absolute_url }}"><strong>{{ guide.get_fullname }}</strong></a>
                        <p>{% if guide.phone %}{{ guide.phone }}{% endif %} {% if guide.email %}-
                            {{ guide.email }}{% endif %}</p>
                    </li>
                {% endfor %}
            </ul>
        </section>
    {% endif %}

    {% if restaurants %}
        <section class="section gallery-list mt-4">
            <header class="section-header">
                <h1>Где поесть?</h1>
                <p>Получите актуальную информацию о ресторанах и кафе в городе и районе Шахрисабз.</p>
                <a href="{% url 'records:restaurant-list' %}" class="btn btn-primary btn-outline btn-small">Больше</a>
            </header>
            <ul class="horizontal mt-2">
                {% if restaurants %}
                    {% for restaurant in restaurants %}
                        <li class="vertical-card">
                            <article style="background-image: url('{{ restaurant.main_image.url }}')">
                                <div class="info">
                                    <header>
                                        <h1><a href="{{ restaurant.get_absolute_url }}">{{ restaurant.title }}</a></h1>
                                        <p>{{ restaurant.description }}</p>
                                    </header>
                                </div>
                            </article>
                        </li>
                    {% endfor %}
                {% endif %}
            </ul>
        </section>
    {% endif %}

{% endblock content %}

templates/organization.html
{% extends 'layouts/base.html' %}
{% load extras %}

{% block content %}
    <header class="full-bleed">
        {% categories %}
    </header>

    <ul class="section breadcrumbs mt-2 mb-2">
        <li><a href="{% url 'records:index' %}">Главная</a></li>
        <li><a href="{% url 'records:organization-list' %}">Все организации</a></li>
        <li>{{ organization.title | truncatechars:20 }}</li>
    </ul>

    <main class="section page-hotels">
        <header>
            <h1>{{ organization.title }}</h1>
            <address><i class="fa-solid fa-location-dot"></i> {{ organization.address }}</address>
        </header>

        {% if organization.organizationimage_set.all %}
            <ul class="gallery mt-2">
                {% for item in organization.organizationimage_set.all %}
                    <li><img src="{{ item.image.url }}" alt="{{ image.caption }}"/></li>
                {% endfor %}
            </ul>
        {% endif %}

        {% if organization.description %}
            <section>
                <h3>Описание</h3>
                <p>{{ organization.description }}</p>
            </section>
        {% endif %}

        <section class="map">
            <h3>Местоположение на карте</h3>
            <div id="map" style="width: 100%; height: 500px"></div>
        </section>
    </main>

    <script>
        let orgLoc = '{{ organization.location }}'.split(',')

        let map = L.map('map').setView([orgLoc[0], orgLoc[1]], 13);

        L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
            maxZoom: 19,
            attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
        }).addTo(map);

        let marker = L.marker([
            orgLoc[0],
            orgLoc[1]
        ]).addTo(map);
    </script>
{% endblock content %}

templates/search.html
{% extends 'layouts/base.html' %}
{% load extras %}

{% block content %}

    <header class="full-bleed">
        {% categories %}
    </header>

    <ul class="section breadcrumbs">
        <li><a href="{% url 'records:index' %}">Главная</a></li>
        <li><p>Результаты поиска для запроса "{{ query }}"</p></li>
    </ul>

    <main class="section page-news">
        <h1>Результаты поиска для запроса "{{ query }}"</h1>
        <ul class="card">
            {% if guides %}
                {% for guide in guides %}
                    <li>
                        <article>
                            <h3><a href="{{ guide.get_absolute_url }}">{{ guide.get_fullname }}</a></h3>
                            <p><a href="{% url "records:index" %}">Гиды</a></p>
                        </article>
                    </li>
                {% endfor %}
            {% endif %}

            {% if hotels %}
                {% for hotel in hotels %}
                    <li>
                        <article>
                            <h3><a href="{{ hotel.get_absolute_url }}">{{ hotel.title }}</a></h3>
                            <p><a href="{% url "records:hotel-list" %}">Отели</a></p>
                        </article>
                    </li>
                {% endfor %}
            {% endif %}

            {% if organizations %}
                {% for organization in organizations %}
                    <li>
                        <article>
                            <h3><a href="{{ organization.get_absolute_url }}">{{ organization.title }}</a></h3>
                            <p><a href="{% url "records:organization-list" %}">Организации</a></p>
                        </article>
                    </li>
                {% endfor %}
            {% endif %}

            {% if pois %}
                {% for poi in pois %}
                    <li>
                        <article>
                            <h3><a href="{{ poi.get_absolute_url }}">{{ poi.title }}</a></h3>
                            <p><a href="{% url "records:poi-list" %}">Точки интереса</a></p>
                        </article>
                    </li>
                {% endfor %}
            {% endif %}

            {% if posts %}
                {% for post in posts %}
                    <li>
                        <article>
                            <h3><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
                            <p><a href="{% url "records:post-list" %}">Публикации</a></p>
                        </article>
                    </li>
                {% endfor %}
            {% endif %}

            {% if transports %}
                {% for transport in transports %}
                    <li>
                        <article>
                            <h3><a href="{{ transport.get_absolute_url }}">{{ transport.model }} - {{ transports.driver }}</a></h3>
                            <p><a href="{% url "records:transport-list" %}">Транспорт</a></p>
                        </article>
                    </li>
                {% endfor %}
            {% endif %}

            {% if events %}
                {% for event in events %}
                    <li>
                        <article>
                            <h3><a href="{{ event.get_absolute_url }}">{{ event.title }}</a></h3>
                            <p><a href="{% url "records:events-list" %}">Мероприятия</a></p>
                        </article>
                    </li>
                {% endfor %}
            {% endif %}


            {% if tours %}
                {% for tour in tours %}
                    <li>
                        <article>
                            <h3><a href="{{ tour.get_absolute_url }}">{{ tour.title }}</a></h3>
                            <p><a href="{% url "records:tour-list" %}">Туры</a></p>
                        </article>
                    </li>
                {% endfor %}
            {% endif %}
        </ul>
    </main>

{% endblock content %}